---
exclude:
  - "CHANGELOG.md"
  - "LICENSE"
  - "README.md"
  - "codemagic.yaml"
  - "mp.rnnn"

restylers:
  - autopep8
  - black
  - prettier-markdown
  - prettier-yaml
  - reorder-python-imports
  - shellharden
  - shfmt
  - yapf
