workflows:
  JNI Libs macOS silicone:
    name: build-macos-jni-artifact
    instance_type: mac_mini_m1
    environment:
      java: 17
#    triggering:
#      events:
#        - push
#        - pull_request
    scripts:
        - brew install git automake yasm nasm

        - |
          ls -al
          id
          pwd
          ./ci_scripts/deps_macos.sh

        - |
          ls -al
          id
          pwd
          ./ci_scripts/java_jni_lib_macos.sh

        - pwd
        - find . -name 'libffmpeg_av_jni.jnilib'
        - ls -al /Users/builder/clone/libffmpeg_av_jni.jnilib
        - mv -v /Users/builder/clone/libffmpeg_av_jni.jnilib /Users/builder/clone/libffmpeg_av_jni_arm64.jnilib

    artifacts:
      - /Users/builder/clone/libffmpeg_av_jni_arm64.jnilib
