# syntax=docker/dockerfile:1
FROM ubuntu:22.04

RUN export DEBIAN_FRONTEND=noninteractive  ; apt update && apt install -y make    yasm curl   wget    git    coreutils    autoconf    libtool    pkg-config    libsodium-dev     nano    vim
RUN mkdir -p /workspace2/build/
RUN cd /workspace2/build/;FFMPEG_VERSION="n7.0.2" ; FFMPEG_FILENAME="$FFMPEG_VERSION"".tar.gz" ;rm -f "ffmpeg"*.tar.*;wget "https://github.com/FFmpeg/FFmpeg/archive/refs/tags/$FFMPEG_FILENAME" -O "ffmpeg_""$FFMPEG_FILENAME";tar -xf "ffmpeg_""$FFMPEG_FILENAME";rm -f "ffmpeg"*.tar.*
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y libx11-xcb-dev libpulse-dev alsa-utils libasound2-dev v4l-utils libv4l-dev v4l-conf
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y openjdk-17-jdk-headless
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y libxcb-shm0-dev libxcb-shape0-dev libxcb-xfixes0-dev
RUN export DEBIAN_FRONTEND=noninteractive ; apt install -y faketime

RUN hostname
RUN domainname

RUN cd /workspace2/build/ && mkdir /workspace2/build/inst/ && \
    cd ./*mpeg*/ && \
    faketime "2023-10-10 08:00:00" ./configure  \
              --enable-gpl \
              --prefix="/workspace2/build/inst/" \
              --disable-asm \
              --extra-cflags=" -fdebug-prefix-map=/workspace2/build=/ -static -O2 -g0 -D_FORTIFY_SOURCE=2 -fstack-protector-strong" \
              --extra-ldflags=" -fdebug-prefix-map=/workspace2/build=/ -lm -fstack-protector-strong" \
              --disable-network \
              --disable-everything \
              --disable-debug \
              --disable-shared \
              --disable-protocols \
              --disable-doc \
              --disable-sdl2 \
              --disable-filters \
              --disable-iconv \
              --disable-network \
              --disable-postproc \
              --disable-swscale-alpha \
              --disable-dwt \
              --disable-lsp \
              --disable-faan \
              --disable-vaapi \
              --disable-vdpau \
              --disable-zlib \
              --disable-bzlib \
              --disable-lzma \
              --disable-encoders \
              --disable-decoders \
              --disable-demuxers \
              --disable-parsers \
              --disable-bsfs \
              --enable-pic \
              --enable-swscale \
              --enable-swresample \
              --enable-avcodec \
              --enable-outdev=alsa \
              --enable-outdev=pulse \
              --enable-indev=alsa \
              --enable-indev=xcbgrab \
              --enable-decoder=mjpeg \
              --enable-demuxer=rawvideo \
              --enable-decoder=rawvideo \
              --enable-demuxer=pcm_s16le \
              --enable-decoder=pcm_s16le \
              --enable-filter=volume \
              --enable-filter=speechnorm \
              --enable-filter=loudnorm \
              --enable-filter=arnndn \
              --enable-filter=afftdn \
              --enable-filter=aresample \
              --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape \
              --enable-indev=pulse \
              --enable-indev=v4l2 \
              --enable-libpulse \
              --enable-runtime-cpudetect \
              --enable-libv4l2 && \
    make -j$(nproc) && \
    make install

RUN ls -al /workspace2/build/inst/lib/

