name: macos JNI Lib

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-macos-nightly-artifact:
    name: Nightly Artifact macOS Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: show architecture
        run:  uname -m

      - name: install deps
        run:  brew install git automake yasm nasm

      - name: build
        run:  |
          ls -al
          id
          pwd
          gcc -framework Foundation -framework CoreFoundation -framework AVFoundation avfoundation_list_devices.m -o avfoundation_list_devices

      - name: run
        run:  |
          ls -al
          id
          pwd
          ./avfoundation_list_devices





