name: macos JNI Lib

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-macos-nightly-artifact:
    name: Nightly Artifact macOS Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: show architecture
        run:  uname -m

      - name: build deps
        run:  |
          ls -al
          id
          pwd
          gcc -framework AVFoundation -framework Foundation -framework CoreGraphics avfoundation_list_devices.m -fsanitize=address -o a

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./a




