name: windows JNI Lib

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:

  build-windows-nightly-artifact:
    name: Nightly Artifact windows Build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          make curl wget git nano vim \

      - name: build deps
        run:  |
          ls -al
          id
          pwd
          cd .localrun/
          ./docker_it_win.sh build

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          cd .localrun/
          ./docker_it_win.sh

      - name: show if home directory is the base directory
        run:  |
          pwd
          cd ~/
          pwd

      - name: copy artefact
        run:  |
          pwd
          cd .localrun/
          find . -name 'ffmpeg_av_jni.dll'
          find . -name 'test.exe'
          cp -v ./windows_ub22/artefacts/ffmpeg_av_jni.dll /home/runner/work/ffmpeg_av_jni/ffmpeg_av_jni/
          cp -v ./windows_ub22/artefacts/test.exe /home/runner/work/ffmpeg_av_jni/ffmpeg_av_jni/

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ffmpeg_av_jni.dll
          path: ffmpeg_av_jni.dll
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "ffmpeg_av_jni.dll,test.exe"

