name: macos arm JNI Lib

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-macos-arm-nightly-artifact:
    name: Nightly Artifact macOS arm Build
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run:  brew install git automake yasm nasm

      - name: build deps
        run:  |
          ls -al
          id
          pwd
          ./ci_scripts/deps_macos.sh

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./ci_scripts/java_jni_lib_macos.sh

      - name: Rename artifact for nightly upload
        run: |
          pwd
          cp -v libffmpeg_av_jni.jnilib libffmpeg_av_jni_arm64.jnilib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libffmpeg_av_jni_arm64.jnilib
          path: libffmpeg_av_jni_arm64.jnilib

      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "libffmpeg_av_jni_arm64.jnilib"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test_macos_arm
          path: test_macos_arm


